# Makefile autogenerated by premake
# Don't edit this file! Instead edit `premake.lua` then rerun `make`
# Options:
#   CONFIG=[Debug|Release]

ifndef CONFIG
  CONFIG=Debug
endif

export CONFIG

.PHONY: all clean stfeatures

all: stfeatures

Makefile: stipcv.lua stfeatures/stfeatures.lua
	@echo ==== Regenerating Makefiles ====
	@premake --file $^ --target gnu

stfeatures:
	@echo ==== Building stfeatures ====
	@$(MAKE) --no-print-directory -C stfeatures

clean:
	@$(MAKE) --no-print-directory -C stfeatures clean
